---

  - name: Get the current firewalld rules
    shell: firewall-cmd --list-all
    register: firewalldrules
    always_run: yes
    sudo: yes

  - name: Add http firewalld rules
    command: firewall-cmd --zone=public --add-service=http --permanent
    sudo: yes
    when: firewalldrules.stdout.find("http") == -1

  - name: Enable firewalld port forwarding
    command: firewall-cmd --zone=public --add-masquerade --permanent
    sudo: yes
    when: firewalldrules.stdout.find("http") == -1

  - name: Portforward 80 to 8000
    command: firewall-cmd --zone=public --add-forward-port=port=80:proto=tcp:toport=8000 --permanent
    sudo: yes
    when: firewalldrules.stdout.find("http") == -1

  - name: Portforward 443 to 4433
    command: firewall-cmd --zone=public --add-forward-port=port=443:proto=tcp:toport=4433 --permanent
    sudo: yes
    when: firewalldrules.stdout.find("http") == -1

  - name: Reload firewalld
    command: firewall-cmd --reload
    sudo: true

  - name: "Add {{ django_aa_user }} user"
    user:
      name: "{{ django_aa_user }}"
      password: "{{ django_aa_hashed_password }}"
      group: apache
    sudo: yes

  - name: Install Python 3
    yum:
      pkg: python34
      state: latest
    sudo: yes

  - name: Install Python-devel
    yum:
      pkg: python-devel
      state: latest
    sudo: yes

  - name: Install Python34-devel
    yum:
      pkg: python34-devel
      state: latest
    sudo: yes

  - name: Install VirtualEnv
    yum:
      pkg: python-virtualenv
      state: latest
    sudo: yes

  - name: Install virtualenvwrapper
    yum:
      pkg: python-virtualenvwrapper
      state: latest
    sudo: yes

  - name: Download get-pip.py
    shell: "chdir={{ django_aa_home }} wget --timeout 120 https://bootstrap.pypa.io/get-pip.py -O get-pip.py"
    become_user: "{{ django_aa_user }}"
    register: get_url_result
    until: get_url_result.stdout.find("Unable to establish SSL connection") == -1
    retries: 2
    delay: 10

  - name: Install pip
    shell: "chdir={{ django_aa_home }} /bin/python3.4 get-pip.py"

  # The virtualenv installed above is broken so we update it here
  - name: Upgrade virtualenv
    shell: pip install --upgrade virtualenv

  - name: Create the initial virtualenv
    become_user: "{{ django_aa_user }}"
    command: virtualenv aa_env -p /bin/python3.4 creates="{{  django_aa_home }}aa_env"

  - name : Check Out AA from git
    become_user: "{{ django_aa_user }}"
    git:
      repo: https://github.com/AnalyticsAutomated/analytics_automated.git
      dest: "{{ django_aa_home }}analytics_automated"
      clone: yes
      force: yes

  - name: Install requirements
    pip:
      chdir: "{{ django_aa_home }}"
      virtualenv: "{{ django_aa_home }}aa_env"
      virtualenv_command: /bin/virtualenv
      virtualenv_python: "{{ django_aa_home }}aa_env/bin/python"
      requirements: "{{ django_aa_home }}analytics_automated/requirements/staging.txt"

  - name: Copy aa staging_conf
    copy:
      src: secrets/staging.py
      dest: "{{ django_aa_home }}/analytics_automated/analytics_automated_project/settings/"
      owner: "{{ django_aa_user }}"

  - name: Copy aa staging secrets
    copy:
      src: secrets/staging_secrets.json
      dest: "{{ django_aa_home }}/analytics_automated/analytics_automated_project/settings/"
      owner: "{{ django_aa_user }}"

  - name: Copy aa base secrets
    copy:
      src: secrets/base_secrets.json
      dest: "{{ django_aa_home }}/analytics_automated/analytics_automated_project/settings/"
      owner: "{{ django_aa_user }}"

  # - name: Copy aa wsgi.py

  - name: Make aa logging dir
    file:
      path: "{{ django_aa_home }}/analytics_automated/logs"
      state: directory
      owner: "{{ django_aa_user }}"

  - name: Run Django migrations
    become_user: "{{ django_aa_user }}"
    django_manage:
      command: migrate
      virtualenv: "{{ django_aa_home }}aa_env/"
      settings: analytics_automated_project.settings.staging
      app_path: "{{ django_aa_home }}/analytics_automated/"

  - name: Install mod_wsgi
    pip:
      chdir: "{{ django_aa_home }}"
      virtualenv: "{{ django_aa_home }}aa_env"
      virtualenv_command: /bin/virtualenv
      virtualenv_python: "{{ django_aa_home }}aa_env/bin/python"
      name: mod_wsgi
      version: 4.4.13

  - name: Install mod_wsgi-httpd
    pip:
      chdir: "{{ django_aa_home }}"
      virtualenv: "{{ django_aa_home }}aa_env"
      virtualenv_command: /bin/virtualenv
      virtualenv_python: "{{ django_aa_home }}aa_env/bin/python"
      name: mod_wsgi-httpd
      version: 2.4.12.6

  - name: stat php.conf
    stat: path=/etc/httpd/conf.d/php.conf
    register: php_stat

  - name: Move php.conf
    command: mv /etc/httpd/conf.d/php.conf /etc/httpd/conf.d/php.conf~
    when: php_stat.stat.exists

  - name: Get the current firewalld rules
    shell: ps aux | grep httpd
    register: aa_running
    always_run: yes
    sudo: yes

  - name : Start AA/Apache
    shell: "chdir={{ django_aa_home }}analytics_automated source {{ django_aa_home}}aa_env/bin/activate; python manage.py runmodwsgi --threads=10 --processes=4 --settings=analytics_automated_project.settings.staging &"
    become_user: "{{ django_aa_user }}"
    register: aa_started
    when: firewalldrules.stdout.find("httpd (mod_wsgi-express)") == -1
