---
  - name: "Add {{ django_aa_user }} user"
    user:
      name: "{{ django_aa_user }}"
      password: "{{ django_aa_hashed_password }}"
      group: apache
    sudo: yes

  - name: Check pip install
    shell: pip --version
    register: pip_install
    always_run: yes
    sudo: yes

  # - name: Download get-pip.py
  #   shell: "chdir={{ django_aa_home }} wget --timeout 120 https://bootstrap.pypa.io/get-pip.py -O get-pip.py"
  #   become_user: "{{ django_aa_user }}"
  #   register: get_url_result
  #   until: get_url_result.stdout.find("Unable to establish SSL connection") == -1
  #   retries: 2
  #   delay: 10
  #   when: pip_install.stdout.find("from /usr/lib/python3.4/site-packages (python 3.4)") == -1

  - name: Download get-pip.py
    become_user: "{{ django_aa_user }}"
    when: pip_install.stdout.find("from /usr/lib/python3.4/site-packages (python 3.4)") == -1
    get_url:
      url: https://bootstrap.pypa.io/get-pip.py
      dest: "{{  django_aa_home }}/get-pip.py"
      timeout: 120
    register: get_url_result
    # until: get_url_result.stdout.find("Unable to establish SSL connection") == -1
    # retries: 2
    # delay: 10

  - name: Install pip
    shell: "chdir={{ django_aa_home }} /bin/python3.4 get-pip.py"
    when: pip_install.stdout.find("from /usr/lib/python3.4/site-packages (python 3.4)") == -1

  # The virtualenv installed above is broken so we update it here
  - name: Upgrade virtualenv
    shell: pip install --upgrade virtualenv

  - name: Check if we have aa_env
    stat: "path={{ django_aa_home }}/aa_env"
    become_user: root
    register: aa_env_exist

  - name: Create the aa head virtualenv
    become_user: "{{ django_aa_user }}"
    command: virtualenv aa_env -p /bin/python3.4
    when: aa_env_exist.stat.exists == False
    args:
        chdir: "{{ django_aa_home }}"

  - name : Check Out AA from git
    become_user: "{{ django_aa_user }}"
    git:
      repo: https://github.com/AnalyticsAutomated/analytics_automated.git
      dest: "{{ django_aa_home }}analytics_automated"
      clone: yes
      force: yes

  - name: Install requirements
    become_user: "{{ django_aa_user }}"
    pip:
      chdir: "{{ django_aa_home }}"
      virtualenv: "{{ django_aa_home }}aa_env"
      virtualenv_command: /bin/virtualenv
      virtualenv_python: "{{ django_aa_home }}aa_env/bin/python"
      requirements: "{{ django_aa_home }}analytics_automated/requirements/staging.txt"

  - name: Copy aa staging_conf
    copy:
      src: secrets/staging.py
      dest: "{{ django_aa_home }}/analytics_automated/analytics_automated_project/settings/"
      owner: "{{ django_aa_user }}"

  - name: Copy aa staging secrets
    copy:
      src: secrets/staging_secrets.json
      dest: "{{ django_aa_home }}/analytics_automated/analytics_automated_project/settings/"
      owner: "{{ django_aa_user }}"

  - name: Copy aa base secrets
    copy:
      src: secrets/base_secrets.json
      dest: "{{ django_aa_home }}/analytics_automated/analytics_automated_project/settings/"
      owner: "{{ django_aa_user }}"

  - name: Copy wsgi.py
    copy:
      src: files/wsgi.py
      dest: "{{ django_aa_home }}/analytics_automated/analytics_automated_project/"
      owner: "{{ django_aa_user }}"

  - name: Make aa logging dir
    file:
      path: "{{ django_aa_home }}/analytics_automated/logs"
      state: directory
      owner: "{{ django_aa_user }}"

  - name: Make jointly visible submissions dir on the NFS
    file:
      path: "/webdata/submissions"
      state: directory
      owner: "{{ django_aa_user }}"
      group: apache
      mode: "ug+rw"

  - name: symlink submissions to the aa dir
    file:
      src: /webdata/submissions
      dest: "{{ django_aa_home }}/analytics_automated/submissions"
      state: link
      owner: "{{ django_aa_user }}"
      group: apache
      mode: "ug+rw"

  - name: Run Django migrations
    become_user: "{{ django_aa_user }}"
    django_manage:
      command: migrate
      virtualenv: "{{ django_aa_home }}aa_env/"
      settings: analytics_automated_project.settings.staging
      app_path: "{{ django_aa_home }}/analytics_automated/"

  - name: Run Django collect static
    become_user: "{{ django_aa_user }}"
    django_manage:
      command: collectstatic
      virtualenv: "{{ django_aa_home }}aa_env/"
      settings: analytics_automated_project.settings.staging
      app_path: "{{ django_aa_home }}/analytics_automated/"

  - name: Get the current list of processes
    shell: ps aux | grep httpd
    register: aa_running
    always_run: yes
    sudo: yes

  - name: Make the apachedir
    file:
      path: "/opt/aa_httpd/"
      state: directory
      owner: "{{ django_aa_user }}"
      group: apache

  - name : Configure AA/Apache
    shell: "source {{ django_aa_home }}aa_env/bin/activate; python manage.py runmodwsgi --settings=analytics_automated_project.settings.staging --setup-only --user django_aa --group apache --threads=10 --processes=4 --reload-on-changes --server-root=/opt/aa_httpd/"
    args:
      chdir: "{{ django_aa_home }}analytics_automated"
    become_user: "{{ django_aa_user }}"
    register: aa_started
    when: aa_running.stdout.find("httpd (mod_wsgi-express)") == -1

  - name : Start aa
    shell: "/opt/aa_httpd/apachectl start"
    become_user: "{{ django_aa_user }}"
    when: aa_running.stdout.find("httpd (mod_wsgi-express)") == -1
    environment:
      DRMAA_LIBRARY_PATH: /opt/ogs_src/GE2011.11/lib/linux-x64/libdrmaa.so
      SGE_ROOT: /opt/ogs_src/GE2011.11/

  - name: copy over the aa head service
    sudo: true
    copy:
      src: files/aahead.service
      dest: /etc/systemd/system/
      mode: "uog+x"

  - name: Add service to systemctl
    sudo: true
    shell: systemctl enable aahead.service
