---
  - name: "Add {{ django_aa_user }} user"
    user:
      name: "{{ django_aa_user }}"
      password: "{{ django_aa_hashed_password }}"
      group: apache
    sudo: yes

  - name: Create the initial virtualenv
    become_user: "{{ django_aa_user }}"
    command: virtualenv aa_env -p /bin/python3.4 creates="{{  django_aa_home }}aa_env"

  - name : Check Out AA from git
    become_user: "{{ django_aa_user }}"
    git:
      repo: https://github.com/AnalyticsAutomated/analytics_automated.git
      dest: "{{ django_aa_home }}analytics_automated"
      clone: yes
      force: yes

  - name: Install requirements
    pip:
      chdir: "{{ django_aa_home }}"
      virtualenv: "{{ django_aa_home }}aa_env"
      virtualenv_command: /bin/virtualenv
      virtualenv_python: "{{ django_aa_home }}aa_env/bin/python"
      requirements: "{{ django_aa_home }}analytics_automated/requirements/staging.txt"

  - name: Copy aa staging_conf
    copy:
      src: secrets/staging.py
      dest: "{{ django_aa_home }}/analytics_automated/analytics_automated_project/settings/"
      owner: "{{ django_aa_user }}"

  - name: Copy aa staging secrets
    copy:
      src: secrets/staging_secrets.json
      dest: "{{ django_aa_home }}/analytics_automated/analytics_automated_project/settings/"
      owner: "{{ django_aa_user }}"

  - name: Copy aa base secrets
    copy:
      src: secrets/base_secrets.json
      dest: "{{ django_aa_home }}/analytics_automated/analytics_automated_project/settings/"
      owner: "{{ django_aa_user }}"

  # - name: Copy aa wsgi.py

  - name: Make aa logging dir
    file:
      path: "{{ django_aa_home }}/analytics_automated/logs"
      state: directory
      owner: "{{ django_aa_user }}"

  - name: Run Django migrations
    become_user: "{{ django_aa_user }}"
    django_manage:
      command: migrate
      virtualenv: "{{ django_aa_home }}aa_env/"
      settings: analytics_automated_project.settings.staging
      app_path: "{{ django_aa_home }}/analytics_automated/"

  - name: Install mod_wsgi
    pip:
      chdir: "{{ django_aa_home }}"
      virtualenv: "{{ django_aa_home }}aa_env"
      virtualenv_command: /bin/virtualenv
      virtualenv_python: "{{ django_aa_home }}aa_env/bin/python"
      name: mod_wsgi
      version: 4.4.13

  - name: Install mod_wsgi-httpd
    pip:
      chdir: "{{ django_aa_home }}"
      virtualenv: "{{ django_aa_home }}aa_env"
      virtualenv_command: /bin/virtualenv
      virtualenv_python: "{{ django_aa_home }}aa_env/bin/python"
      name: mod_wsgi-httpd
      version: 2.4.12.6

  - name: Get the current list of processes
    shell: ps aux | grep httpd
    register: aa_running
    always_run: yes
    sudo: yes

  - name : Start AA/Apache
    shell: "chdir={{ django_aa_home }}analytics_automated source {{ django_aa_home}}aa_env/bin/activate; python manage.py runmodwsgi --threads=10 --processes=4 --settings=analytics_automated_project.settings.staging &"
    become_user: "{{ django_aa_user }}"
    register: aa_started
    when: aa_running.stdout.find("httpd (mod_wsgi-express)") == -1
