---
#
# This roles assumes the ogs build worker AND it left behind the tarballs and
# the compiled stuff in /opt/ogs_src/GE2011.11 and /opt/sge6_dist
#

#export SGE_ROOT=/opt/ogs_src/GE2011.11/
  - name: Install expect
    yum:
      pkg: expect
      state: latest
    sudo: yes

#open ports 6444 and 6445

  - name: Get the current firewalld rules
    shell: firewall-cmd --list-all
    register: firewalldrules
    always_run: yes
    sudo: yes

  - name: Add Postgres firewalld rules
    command: firewall-cmd --zone=public --add-port=6444/tcp --permanent
    sudo: yes
    when: firewalldrules.stdout.find("6444"/tcp") == -1

  - name: Add Postgres firewalld rules
    command: firewall-cmd --zone=public --add-port=6445/tcp --permanent
    sudo: yes
    when: firewalldrules.stdout.find("6445"/tcp") == -1

  - name: Reload firewalld
    command: firewall-cmd --reload
    sudo: true

  - name: add ogs_admin group
    group: name=ogs state=present

  - name: "Add {{ ogs_admin_user }}"
    user: "name={{ ogs_admin_user }} password={{ ogs_admin_hashed_password }} group=ogs"
    sudo: yes

  - name: Check if we have default cluster config present
    stat: "path=/opt/ogs_src/GE2011.11/default/"
    become_user: root
    register: default_present

  - name: add the ogs directory
    file: path=/opt/ogs_src/GE2011.11 state=directory
    become_user: {{ ogs_admin_user }}
    when: default_present == -1

  - name: move default dir
    when: default_present == -1
    become_user: {{ ogs_admin_user }}
    shell: mv /tmp/default /opt/ogs_src/GE2011.11

  - name: move common tar
    become_user: {{ ogs_admin_user }}
    shell: mv /tmp/ge-GE2011.11-common.tar.gz /opt/ogs_src/GE2011.11
    when: default_present == -1

  - name: move x86_64 tar
    become_user: {{ ogs_admin_user }}
    shell: mv /tmp/ge-GE2011.11-bin-linux-x64.tar.gz /opt/ogs_src/GE2011.11
    when: default_present == -1

  - name: untar common
    become_user: {{ ogs_admin_user }}
    shell: "cd /opt/ogs_src/GE2011.11; tar -zxvf ge-GE2011.11-common.tar.gz"
    when: default_present == -1

  - name: untar x86_64
    become_user: {{ ogs_admin_user }}
    shell: "cd /opt/ogs_src/GE2011.11; tar -zxvf ge-GE2011.11-bin-linux-x64.tar.gz"
    when: default_present == -1

  - name: Move execd expect script
    become_user: root
    copy:
      src: files/execd_setup.exp
      dest: /opt/ogs_src/GE2011.11

  - name: Run install_exced expect script
    become_user: root
    shell: "cd /opt/ogs_src/GE2011.11/; /opt/ogs_src/GE2011.11/execd_setup.exp"
    when: default_present == -1

  # - name: restart execd
  #   shell: service sgemaster.p6444 stop && sgemaster.p6444 start
  #   when: default_present == 1
