---

  - name: Install Dependencies
    yum:
      pkg: redis
      state: latest
    sudo: yes

  - name: "Add {{ redis_user }}"
    user: "name={{ redis_user }} password={{ redis_hashed_password }}"
    sudo: yes

  - name: Get the current firewalld rules
    shell: firewall-cmd --list-all
    register: firewalldrules
    always_run: yes
    sudo: yes

  - name: Add Redis firewalld rules
    command: firewall-cmd --zone=public --add-port=6379/tcp --permanent
    sudo: yes
    when: firewalldrules.stdout.find("6379/tcp") == -1

  - name: Reload firewalld
    command: firewall-cmd --reload
    sudo: true

  - name: Check redis-server status
    shell: ps aux | grep redis-server
    register: redis_running
    always_run: yes

  - name: Start redis
    command: "/bin/redis-server --daemonize yes"
    become_user: "{{ redis_user }}"
    when: redis_running.stdout.find("redis-server") == -1

  - name: copy over the redis systemd service
    sudo: true
    copy:
      src: files/redis.service
      dest: /etc/systemd/system/
      mode: "uog+x"

  - name: Add service to systemctl
    sudo: true
    shell: systemctl enable redis.service
