---
# ansible-playbook -i staging deploy_staging.yml -f 1
#
#  WARNING! YOU MUST HAVE A COMPLETE secrets/
#  YOU MUST HAVE files/jdk-8u60-linux-x64.tar.gz
#

# - name: Set up mount point
#   hosts: everyone
#   become: true
#   become_user: dbuchan
#   become_method: sudo
#   roles:
#     - automount
#     - update nss and curl # yum update -y nss curl libcurl
#   vars_files:
#     - secrets/staging_secrets.yaml
#
# - name: Apply the redis configuration
#   hosts: redis
#   become: true
#   become_user: dbuchan
#   become_method: sudo
#   roles:
#    - redis
#   vars_files:
#    - secrets/staging_secrets.yaml
#
# - name: Apply the postgres configuration
#   hosts: dbserver
#   become: true
#   become_user: dbuchan
#   become_method: sudo
#   roles:
#     - dbserver
#   vars_files:
#     - secrets/staging_secrets.yaml

# - name: Apply Analytics Automated head node configuration
#   hosts: aa_head
#   become: true
#   become_user: dbuchan
#   become_method: sudo
#   roles:
#     - djangomachine
#     - aahead
#   vars_files:
#     - secrets/staging_secrets.yaml

# - name: Apply Analytics Automated worker node configuration
#   hosts: aa_workers
#   become: true
#   become_user: dbuchan
#   become_method: sudo
#   roles:
#     # - djangomachine
#     - aaworker
#   vars_files:
#     - secrets/staging_secrets.yaml

# - name: Create SGE head
#   hosts: sge_head
#   become: true
#   become_user: dbuchan
#   become_method: sudo
#   roles:
#     #- buildsge
#     - sgehead
#   vars_files:
#     - secrets/staging_secrets.yaml

# - name: Create blastmachine
#   hosts: blastmachine
#   become: true
#   become_user: root
#   become_method: sudo
#   roles:
#     # - djangomachine
#     # - blastmachine
#     - blastworkers
#   vars_files:
#     - secrets/staging_secrets.yaml

# - name: Create blast_cache machine
#   hosts: blast_cache
#   become: true
#   become_user: root
#   become_method: sudo
#   roles:
#     # - djangomachine
#     - blastcache
#   vars_files:
#     - secrets/staging_secrets.yaml

# mempack won't compile in OSX
# domThreader seg faults in OSX
- name: Create SGE node
  hosts: sge_node
  become: true
  become_user: root
  become_method: sudo
  roles:
    # - sgenode
    # - psipred
    # - disopred
    # - memsatsvm
    # - pGenTHREADER # installed to /webdata due to space on bioinfstage4
    # - model_parts # get the bits for the frontend simple modelling
    # - dompred # installed to /webdata due to space on bioinfstage4

    - mempack
    - bioserf
    - ffpred
    - metapsicov
    - metsite
    - hspred
    - memembed
    - maketdb
  vars_files:
    - secrets/staging_secrets.yaml

# - name: Install webserver
#   hosts: webserver
#   become: true
#   become_user: dbuchan
#   become_method: sudo
#   roles:
#     - djangomachine
#     - webserver
#   vars_files:
#     - secrets/staging_secrets.yaml
