---
# ansible-playbook -i staging deploy_staging.yml -f 1
#
#  WARNING! YOU MUST HAVE A COMPLETE secrets/
#  YOU MUST HAVE files/jdk-8u60-linux-x64.tar.gz
#

# - name: Set up mount point
#   hosts: everyone
#   user: dbuchan
#   sudo: yes
#   roles:
#     - automount
#   vars_files:
#     - secrets/staging_secrets.yaml
#
# - name: Apply the rabbit_mq configuration
#   hosts: rabbit_mq
#   user: dbuchan
#   sudo: yes
#   roles:
#    - rabbitmq
#   vars_files:
#    - secrets/staging_secrets.yaml
#
# - name: Apply the postgres configuration
#   hosts: dbserver
#   user: dbuchan
#   sudo: yes
#   roles:
#     - dbserver
#   vars_files:
#     - secrets/staging_secrets.yaml
#
# - name: Apply Analytics Automated head node configuration
#   hosts: aa_head
#   user: dbuchan
#   sudo: yes
#   roles:
#     - djangomachine
#     - aahead
#   vars_files:
#     - secrets/staging_secrets.yaml
#
# - name: Apply Analytics Automated worker node configuration
#   hosts: aa_workers
#   user: dbuchan
#   sudo: yes
#   roles:
#     - djangomachine
#     - aaworker
#   vars_files:
#     - secrets/staging_secrets.yaml

# - name: Create SGE head
#   hosts: sge_head
#   user: dbuchan
#   sudo: yes
#   roles:
#     #- buildsge
#     - sgehead
#   vars_files:
#     - secrets/staging_secrets.yaml
#
- name: Create SGE node
  hosts: sge_node
  user: dbuchan
  sudo: yes
  roles:
    # - sgenode
    # - blastmachine
    # - psipred
    # - disopred
    # - memsatsvm
    # - pGenTHREADER # installed to /webdata due to space on bioinfstage4
    # - pDomTHREADER # installed to /webdata due to space on bioinfstage4
    # - genTHREADER # installed to /webdata due to space on bioinfstage4
    # - dompred # installed to /webdata due to space on bioinfstage4
    # - mempack
    # - metsite
    # - hspred
    # - memembed
    # - maketdb
    - bioserf #package includes all the domserf code too

    # - ffpred URGH

  vars_files:
    - secrets/staging_secrets.yaml

# - name: Install webserver
#   hosts: webserver
#   user: dbuchan
#   sudo: yes
#   roles:
#     - djangomachine
#     - webserver
#   vars_files:
#     - secrets/staging_secrets.yaml
