# ansible-playbook -i staging restart_aa.yml -f 1


- name: Restart django aa on the aahead
  hosts: aa_head
  user: dbuchan
  sudo: yes
  roles:
   - restart_aa
  vars_files:
   - secrets/staging_secrets.yaml

- name: Apply the postgres configuration
  hosts: aa_workers
  user: dbuchan
  sudo: yes
  roles:
    - aaworker
  vars_files:
    - secrets/staging_secrets.yaml
