---

  - name: "install erlang"
    yum:
      pkg: erlang
      state: latest
    sudo: yes

  - name: Download rabbitMQ tarball
    get_url: url=https://www.rabbitmq.com/releases/rabbitmq-server/v3.5.4/rabbitmq-server-generic-unix-3.5.4.tar.gz dest=/home/dbuchan/rabbitmq-server-generic-unix-3.5.4.tar.gz
    register: get_url_result

  - name: untar the tarball
    shell: tar -zxvf /home/dbuchan/rabbitmq-server-generic-unix-3.5.4.tar.gz
    when: get_url_result.changed

  - name: "Add {{ rabbit_user }}"
    user: "name={{ rabbit_user }} password={{ rabbit_hashed_password }}"
    sudo: yes

  - name: Get the current firewalld rules
    shell: firewall-cmd --list-all
    register: firewalldrules
    always_run: yes
    sudo: yes

  - name: Add Rabbit firewalld rules
    command: firewall-cmd --zone=public --add-port=4369/tcp --permanent
    sudo: yes
    when: firewalldrules.stdout.find("4369/tcp") == -1

  - name: Add Erlang firewalld rules
    command: firewall-cmd --zone=public --add-port=25672/tcp --permanent
    sudo: yes
    when: firewalldrules.stdout.find("25672/tcp") == -1

  - name: Add AMQP firewalld rules
    command: firewall-cmd --zone=public --add-port=567-5672/tcp --permanent
    sudo: yes
    when: firewalldrules.stdout.find("25672/tcp") == -1

  - name: Reload firewalld
    command: firewall-cmd --reload
    sudo: true
