---

  - name: "install erlang"
    yum:
      pkg: erlang
      state: latest
    sudo: yes

  - name: "Add {{ rabbit_user }}"
    user: "name={{ rabbit_user }} password={{ rabbit_hashed_password }}"
    sudo: yes

  # we switched to using wget as get_url: has no adjustable timeout and is
  # fixed to 10secs!?!?
  - name: Check if we have the rabbitMQ tarball already
    stat: "path=/home/{{ rabbit_user }}/rabbitmq-server-generic-unix-3.5.4.tar.gz"
    register: rabbit_tarball_exist

  - name: Download rabbitMQ tarball
    # get_url: "url=https://www.rabbitmq.com/releases/rabbitmq-server/v3.5.4/rabbitmq-server-generic-unix-3.5.4.tar.gz dest=/home/{{ rabbit_user }}/rabbitmq-server-generic-unix-3.5.4.tar.gz"
    shell: "chdir=/home/{{ rabbit_user }} wget https://www.rabbitmq.com/releases/rabbitmq-server/v3.5.4/rabbitmq-server-generic-unix-3.5.4.tar.gz"
    when: rabbit_tarball_exist.stat.exists == False
    become_user: "{{ rabbit_user }}"
    register: get_url_result
    until: get_url_result
    retries: 2
    delay: 5

  - name: untar the tarball
    shell: "cd /home/{{ rabbit_user }}; tar -zxvf /home/{{ rabbit_user }}/rabbitmq-server-generic-unix-3.5.4.tar.gz"
    become_user: "{{ rabbit_user }}"
    when: get_url_result.changed

  - name: Get the current firewalld rules
    shell: firewall-cmd --list-all
    register: firewalldrules
    always_run: yes
    sudo: yes

  - name: Add Rabbit firewalld rules
    command: firewall-cmd --zone=public --add-port=4369/tcp --permanent
    sudo: yes
    when: firewalldrules.stdout.find("4369/tcp") == -1

  - name: Add Erlang firewalld rules
    command: firewall-cmd --zone=public --add-port=25672/tcp --permanent
    sudo: yes
    when: firewalldrules.stdout.find("25672/tcp") == -1

  - name: Add AMQP firewalld rules
    command: firewall-cmd --zone=public --add-port=567-5672/tcp --permanent
    sudo: yes
    when: firewalldrules.stdout.find("25672/tcp") == -1

  - name: Reload firewalld
    command: firewall-cmd --reload
    sudo: true

  - name: Start rabbitMQ
    command: "/home/{{ rabbit_user }}/rabbitmq-server-generic-unix-3.5.4/sbin/rabbitmq-server --detached"
    become_user: "{{ rabbit_user }}"
