---

  - name: Get the current firewalld rules
    shell: firewall-cmd --list-all
    register: firewalldrules
    always_run: yes
    sudo: yes

  - name: Add http firewalld rules
    command: firewall-cmd --zone=public --add-service=http --permanent
    sudo: yes
    when: firewalldrules.stdout.find("http") == -1

  - name: Enable firewalld port forwarding
    command: firewall-cmd --zone=public --add-masquerade --permanent
    sudo: yes
    when: firewalldrules.stdout.find("http") == -1

  - name: Portforward 80 to 8000
    command: firewall-cmd --zone=public --add-forward-port=port=80:proto=tcp:toport=8000 --permanent
    sudo: yes
    when: firewalldrules.stdout.find("http") == -1

  - name: Portforward 443 to 4433
    command: firewall-cmd --zone=public --add-forward-port=port=443:proto=tcp:toport=4433 --permanent
    sudo: yes
    when: firewalldrules.stdout.find("http") == -1

  - name: Reload firewalld
    command: firewall-cmd --reload
    sudo: true

  - name: Install Python 3
    yum:
      pkg: python34
      state: latest
    sudo: yes

  - name: Install Python-devel
    yum:
      pkg: python-devel
      state: latest
    sudo: yes

  - name: Install Python34-devel
    yum:
      pkg: python34-devel
      state: latest
    sudo: yes

  - name: Install VirtualEnv
    yum:
      pkg: python-virtualenv
      state: latest
    sudo: yes

  - name: Install virtualenvwrapper
    yum:
      pkg: python-virtualenvwrapper
      state: latest
    sudo: yes

  - name: Download get-pip.py
    shell: "chdir={{ django_aa_home }} wget --timeout 120 https://bootstrap.pypa.io/get-pip.py -O get-pip.py"
    become_user: "{{ django_aa_user }}"
    register: get_url_result
    until: get_url_result.stdout.find("Unable to establish SSL connection") == -1
    retries: 2
    delay: 10

  - name: Install pip
    shell: "chdir={{ django_aa_home }} /bin/python3.4 get-pip.py"

  # The virtualenv installed above is broken so we update it here
  - name: Upgrade virtualenv
    shell: pip install --upgrade virtualenv
