---
  - name: "Add {{ django_worker_user }} user"
    user:
      name: "{{ django_worker_user }}"
      password: "{{ django_worker_hashed_password }}"
      group: apache
    sudo: yes

  - name: Create worker virtualenv
    become_user: "{{ django_aa_user }}"
    command: virtualenv aa_env -p /bin/python3.4 creates="{{  django_worker_home }}aa_env"

  - name: Download get-pip.py
    shell: "chdir={{ django_worker_home }} wget --timeout 120 https://bootstrap.pypa.io/get-pip.py -O get-pip.py"
    become_user: "{{ django_worker_user }}"
    register: get_url_result
    until: get_url_result.stdout.find("Unable to establish SSL connection") == -1
    retries: 2
    delay: 10

  - name: Check pip install
    shell: pip --version
    register: pip_install
    always_run: yes
    sudo: yes

  - name: Install pip
    shell: "chdir={{ django_worker_home }} /bin/python3.4 get-pip.py"
    when: pip_install.stdout.find("from /usr/lib/python3.4/site-packages (python 3.4)") == -1

  # The virtualenv installed above is broken so we update it here
  - name: Upgrade virtualenv
    shell: pip install --upgrade virtualenv

  - name: Create the aa head virtualenv
    become_user: "{{ django_worker_user }}"
    command: virtualenv aa_env -p /bin/python3.4 creates="{{  django_worker_home }}aa_env"

  - name : Check Out AA from git
    become_user: "{{ django_worker_user }}"
    git:
      repo: https://github.com/AnalyticsAutomated/analytics_automated.git
      dest: "{{ django_worker_home }}analytics_automated"
      clone: yes
      force: yes

  - name: Install requirements
    pip:
      chdir: "{{ django_worker_home }}"
      virtualenv: "{{ django_worker_home }}aa_env"
      virtualenv_command: /bin/virtualenv
      virtualenv_python: "{{ django_worker_home }}aa_env/bin/python"
      requirements: "{{ django_worker_home }}analytics_automated/requirements/staging.txt"

  - name: Install mod_wsgi
    pip:
      chdir: "{{ django_worker_home }}"
      virtualenv: "{{ django_worker_home }}aa_env"
      virtualenv_command: /bin/virtualenv
      virtualenv_python: "{{ django_worker_home }}aa_env/bin/python"
      name: mod_wsgi
      version: 4.4.13

  - name: Install mod_wsgi-httpd
    pip:
      chdir: "{{ django_worker_home }}"
      virtualenv: "{{ django_worker_home }}aa_env"
      virtualenv_command: /bin/virtualenv
      virtualenv_python: "{{ django_worker_home }}aa_env/bin/python"
      name: mod_wsgi-httpd
      version: 2.4.12.6

  - name: Copy aa staging_conf
    copy:
      src: secrets/staging_worker.py
      dest: "{{ django_worker_home }}/analytics_automated/analytics_automated_project/settings/staging.py"
      owner: "{{ django_worker_user }}"

  - name: Copy aa staging secrets
    copy:
      src: secrets/staging_worker_secrets.json
      dest: "{{ django_worker_home }}/analytics_automated/analytics_automated_project/settings/"
      owner: "{{ django_worker_user }}"

  - name: Copy aa base secrets
    copy:
      src: secrets/base_secrets.json
      dest: "{{ django_worker_home }}/analytics_automated/analytics_automated_project/settings/"
      owner: "{{ django_worker_user }}"

  - name: Copy celery conf
    copy:
      src: files/celery_staging.py
      dest: "{{ django_worker_home }}/analytics_automated/analytics_automated_project/celery.py"
      owner: "{{ django_worker_user }}"

  - name: Make aa logging dir
    file:
      path: "{{ django_worker_home }}/analytics_automated/logs"
      state: directory
      owner: "{{ django_worker_user }}"

# Here we skip running the django migrations as they are only run by aahead
# AND this role MUST come after aahead installation runs

  - name: Start the aa_workers
    shell: "chdir={{ django_worker_home }}/analytics_automated/ source {{ django_worker_home }}aa_env/bin/activate; celery --app=analytics_automated_project.celery:app worker --loglevel=INFO -Q localhost,celery"
    become_user: "{{ django_worker_user }}"
#celery --app=analytics_automated_project.celery:app worker --loglevel=INFO -Q localhost,celery
