---
  - name: "Add {{ django_worker_user }} user"
    user:
      name: "{{ django_worker_user }}"
      password: "{{ django_worker_hashed_password }}"
      group: apache
    sudo: yes

  - name: Create worker virtualenv
    become_user: "{{ django_aa_user }}"
    command: virtualenv aa_env -p /bin/python3.4 creates="{{  django_worker_home }}aa_env"

  - name: Download get-pip.py
    shell: "chdir={{ django_worker_home }} wget --timeout 120 https://bootstrap.pypa.io/get-pip.py -O get-pip.py"
    become_user: "{{ django_worker_user }}"
    register: get_url_result
    until: get_url_result.stdout.find("Unable to establish SSL connection") == -1
    retries: 2
    delay: 10

  - name: Check pip install
    shell: pip --version
    register: pip_install
    always_run: yes
    sudo: yes

  - name: Install pip
    shell: "chdir={{ django_worker_home }} /bin/python3.4 get-pip.py"
    when: pip_install.stdout.find("from /usr/lib/python3.4/site-packages (python 3.4)") == -1

  # The virtualenv installed above is broken so we update it here
  - name: Upgrade virtualenv
    shell: pip install --upgrade virtualenv

  - name : Check Out AA from git
    become_user: "{{ django_worker_user }}"
    git:
      repo: https://github.com/AnalyticsAutomated/analytics_automated.git
      dest: "{{ django_worker_home }}analytics_automated"
      clone: yes
      force: yes

  - name: Install requirements
    pip:
      chdir: "{{ django_worker_home }}"
      virtualenv: "{{ django_worker_home }}aa_env"
      virtualenv_command: /bin/virtualenv
      virtualenv_python: "{{ django_worker_home }}aa_env/bin/python"
      requirements: "{{ django_worker_home }}analytics_automated/requirements/staging.txt"
