#copy auto mount config
  - name: Copy auto.master
    become_user: root
    become_method: sudo
    copy:
      src: files/auto.master
      dest: /etc/auto.master

  - name: Copy auto.bioinf
    become_user: root
    become_method: sudo
    copy:
      src: files/auto.bioinf
      dest: /etc/auto.bioinf

#restart automount
  - name: Restart autofs
    shell: /usr/sbin/service autofs restart
    become_user: root
    become_method: sudo
    check_mode: no

  - name: add chkconfig
    shell: /usr/sbin/chkconfig autofs on
    become_user: root
    become_method: sudo
    check_mode: no
