#copy auto mount config
  - name: Copy auto.bioinf
    become_user: root
    become_method: sudo
    copy:
      src: files/auto.bioinf
      dest: /etc/auto.bioinf

#restart automount
  - name: Restart autofs
    shell: service autofs restart
    always_run: yes
    become_user: root
    become_method: sudo

  - name: add chkconfig
    shell: chkconfig autofs on
    always_run: yes
    become_user: root
    become_method: sudo
