---

  - name: Install postgreSQL
    yum:
      pkg: postgresql
      state: latest
    sudo: yes

  - name: Check if postgresDB location exists
    stat: "path={{ postgres_db_path }}"
    register: postgresDB_exist

  - name: Initialise postgresDB
    shell: "/bin/initdb -D {{ postgres_db_path }}"
    when: postgresDB_exist.stat.exists == False

  - name: Give postgres ownership of db
    file:
      path: {{ postgres_db_path }}
      state: directory
      recurse: yes
      owner: {{ postgres_user }}
