---

  - name: Install postgreSQL
    yum:
      pkg: postgresql
      state: latest
    sudo: yes

  - name: Check if postgresDB location exists
    stat: "path={{ postgres_db_path }}"
    register: postgresDB_exist

  - name: Make postgres db directory
    file:
      path: "{{ postgres_db_path }}"
      state: directory
      owner: "{{ postgres_user }}"
    when: postgresDB_exist.stat.exists == False

  - name: Initialise postgresDB
    shell: "/bin/initdb -D {{ postgres_db_path }}"
    become_user: "{{ postgres_user }}"
    when: postgresDB_exist.stat.exists == False

  - name: Start postgredDB
    shell: "pg_ctl start -D {{ postgres_db_path }}"
    register: postgres_started
