---

  - name: Install libgd
    yum:
      pkg: gd
      state: latest
    sudo: yes

  - name: Install libgd-devel
    yum:
      pkg: gd-devel
      state: latest
    sudo: yes

  - name: Install Round.pm
    cpanm:
      name: Math::Round
      mirror: http://cpan.mirror.triple-it.nl/

  - name: Install GD.pm
    cpanm:
      name: GD
      mirror: http://cpan.mirror.triple-it.nl/

  - name: Check if memsatsvm is installed
    stat: path=/opt/memsat-svm
    register: memsat_exist

  - name : Check Out MEMSATSVM from GIT
    when: memsat_exist.stat.exists == False
    git:
      repo: https://github.com/psipred/MemSatSVM.git
      dest: /opt/memsat-svm
      clone: yes
      force: yes

  # - name: Download memsat model data
  #   when: memsat_exist.stat.exists == False
  #   shell: "chdir=/opt/memsat-svm wget --timeout 120 http://bioinfadmin.cs.ucl.ac.uk/downloads/memsat-svm/models.tar.gz"
  #   register: get_url_result
    # until: get_url_result.stdout.find("Unable to establish SSL connection") == -1
    # retries: 2
    # delay: 10
    # when: pip_install.stdout.find("from /usr/lib/python3.4/site-packages (python 3.4)") == -1

  - name: Download memsat tar ball
    when: memsat_exist.stat.exists == False
    get_url:
      url: http://bioinfadmin.cs.ucl.ac.uk/downloads/memsat-svm/models.tar.gz
      dest: /opt/memsat-svm
      timeout: 120
    register: get_url_result

  - name: untar memsat model data
    when: memsat_exist.stat.exists == False
    unarchive:
      src: /opt/memsat-svm/models.tar.gz
      dest: /opt/memsat-svm/
      remote_src: yes

  - name: make binaries
    shell: "cd /opt/memsat-svm; make"
